name: Go Build Multi-Platform

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        goos: [linux, windows, darwin, freebsd, openbsd, netbsd]
        goarch: [amd64, arm64, 386, ppc64le]
        exclude:
          - goos: windows
            goarch: ppc64le
          - goos: darwin
            goarch: 386
          - goos: darwin
            goarch: ppc64le
          - goos: freebsd
            goarch: arm64
          - goos: freebsd
            goarch: ppc64le
          - goos: openbsd
            goarch: arm64
          - goos: openbsd
            goarch: ppc64le
          - goos: netbsd
            goarch: arm64
          - goos: netbsd
            goarch: ppc64le

    runs-on: ubuntu-latest

    outputs:
      build_complete: ${{ steps.build_step.outcome == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Build
      id: build_step
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        output_name="git-email-extractor-go-${GOOS}-${GOARCH}"
        if [ "$GOOS" = "windows" ]; then
          output_name+=".exe"
        fi
        go build -v -ldflags="-s -w" -o "${output_name}" .
        echo "Built: ${output_name}"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: git-email-extractor-go-${{ matrix.goos }}-${{ matrix.goarch }}
        path: git-email-extractor-go-${{ matrix.goos }}-${{ matrix.goarch }}*

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    permissions:
      contents: write

    steps:
      - name: Download All Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release-assets

      - name: List downloaded files (for debugging)
        run: ls -R ./release-assets

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release-assets/*/*